// Central, bilingual content for the public site.
// German (de-CH) is the primary, server-rendered language used for SEO.

export const SITE = {
  name: "SHAZWERK",
  legalName: "SHAZWERK GmbH",
  url: "https://www.shazwerk.ch",
  email: "hello@shazwerk.ch",
  phone: "+41 44 820 90 10",
  phoneE164: "+41448209010",
  street: "Gotthardstrasse 26",
  zip: "8002",
  city: "Zürich",
  uid: "CHE-419.820.104",
};

/** Shared social preview image (generated by app/opengraph-image.tsx). */
export const OG_IMAGES = [{ url: "/opengraph-image", width: 1200, height: 630, alt: "SHAZWERK – Webagentur & Software Studio Zürich" }];

export type Bi = { de: string; en: string };

export interface Project {
  slug: string;
  num: string;
  client: string;
  title: Bi;
  category: string;
  sector: Bi;
  location: string;
  year: string;
  summary: Bi;
  challenge: Bi;
  solution: Bi;
  outcomes: { de: string[]; en: string[] };
  metrics: { value: string; label: Bi }[];
  tech: string[];
  // Generative poster parameters
  hue: string;
  motif: "grid" | "rings" | "bars" | "cross" | "wave";
}

export const PROJECTS: Project[] = [
  {
    slug: "alpine-dynamics",
    num: "01",
    client: "Alpine Dynamics",
    title: {
      de: "Echtzeit-Telemetrie für den alpinen Kühltransport",
      en: "Real-time telemetry for alpine cold-chain freight",
    },
    category: "Plattform",
    sector: { de: "Logistik & Transport", en: "Logistics & Transport" },
    location: "Chur · DACH",
    year: "2026",
    summary: {
      de: "Telemetrie- und Dispositionsplattform für über 1'400 Kühltransporte im Alpenraum – mit Kartenaktualisierung im Sub-Sekunden-Bereich.",
      en: "Telemetry and dispatch platform for 1,400+ refrigerated freight assets across the Alps, with sub-second map updates.",
    },
    challenge: {
      de: "Die bestehende ERP-Infrastruktur verlor auf Alpentransits regelmässig Daten – ein Compliance-Risiko für pharmazeutische Ladungen.",
      en: "The legacy ERP lost data on high-altitude transits, risking compliance for pharmaceutical cargo.",
    },
    solution: {
      de: "Event-getriebene Telemetrie-Pipeline auf Next.js, WebSockets und geo-replizierter PostgreSQL mit Offline-Pufferung an jedem Fahrzeug.",
      en: "Event-driven telemetry pipeline on Next.js, WebSockets and geo-replicated PostgreSQL, with offline buffering on every vehicle.",
    },
    outcomes: {
      de: [
        "99.994 % Verfügbarkeit über die gesamte Wintersaison",
        "42 % weniger Zollverzögerungen dank digitaler Manifeste",
        "Live-Updates unter 50 ms auf allen Knoten",
      ],
      en: [
        "99.994% availability through the entire winter season",
        "42% fewer customs delays via digital manifests",
        "Sub-50ms live updates across all nodes",
      ],
    },
    metrics: [
      { value: "99.994%", label: { de: "Verfügbarkeit", en: "Uptime" } },
      { value: "1'400+", label: { de: "Fahrzeuge live", en: "Assets live" } },
      { value: "<50ms", label: { de: "Latenz", en: "Latency" } },
    ],
    tech: ["Next.js", "WebSockets", "PostgreSQL", "GIS", "Docker"],
    hue: "#E30613",
    motif: "wave",
  },
  {
    slug: "zurich-fintech",
    num: "02",
    client: "Zurich FinTech Exchange",
    title: {
      de: "Abstimmungs- & Handelsoberfläche für ein FINMA-Institut",
      en: "Reconciliation & trading interface for a FINMA institution",
    },
    category: "FinTech",
    sector: { de: "Finanzmärkte", en: "Financial Markets" },
    location: "Zürich",
    year: "2025",
    summary: {
      de: "Treasury- und Abstimmungsoberfläche mit niedrigster Latenz für einen regulierten Handelsplatz in Zürich – mit kryptografischem Audit-Trail.",
      en: "Ultra-low-latency treasury and reconciliation interface for a regulated Zurich exchange, with a cryptographic audit trail.",
    },
    challenge: {
      de: "In volatilen Sessions führten Millionen von Orderbuch-Updates zu Frame-Drops und Race Conditions im UI.",
      en: "In volatile sessions, millions of order book updates caused frame drops and UI race conditions.",
    },
    solution: {
      de: "Virtualisierungsschicht in WebAssembly mit Canvas-Rendering ohne Repaint und Zero-Trust-Datenfluss.",
      en: "A WebAssembly virtualization layer with zero-repaint canvas rendering and zero-trust data flow.",
    },
    outcomes: {
      de: [
        "Tägliche Abwicklung in unter 15 ms, unabhängig auditiert",
        "Konform mit Bankengesetz und FINMA-Rundschreiben",
        "Lückenloser, kryptografisch gesicherter Audit-Trail",
      ],
      en: [
        "Daily settlement under 15ms, independently audited",
        "Compliant with the Banking Act and FINMA circulars",
        "Complete, cryptographically secured audit trail",
      ],
    },
    metrics: [
      { value: "<15ms", label: { de: "Abwicklung", en: "Settlement" } },
      { value: "0", label: { de: "Frame-Drops", en: "Frame drops" } },
      { value: "FINMA", label: { de: "Audit-sicher", en: "Audit-ready" } },
    ],
    tech: ["WebAssembly", "TypeScript", "Next.js", "Canvas", "Zero Trust"],
    hue: "#141414",
    motif: "bars",
  },
  {
    slug: "lumina-legaltech",
    num: "03",
    client: "Lumina Intelligence",
    title: {
      de: "Souveräner Vertrags-Copilot für Schweizer Kanzleien",
      en: "Sovereign contract copilot for Swiss law firms",
    },
    category: "AI",
    sector: { de: "Legaltech", en: "Legaltech" },
    location: "Zug",
    year: "2026",
    summary: {
      de: "Air-gapped RAG-Architektur in Schweizer Rechenzentren für mehrsprachige Vertragsanalyse – ohne dass ein einziges Dokument die Schweiz verlässt.",
      en: "Air-gapped RAG architecture in Swiss data centres for multilingual contract analysis – no document ever leaves Switzerland.",
    },
    challenge: {
      de: "Das revidierte Datenschutzgesetz (nDSG) verbot den Einsatz kommerzieller Cloud-LLMs für vertrauliche Mandatsunterlagen.",
      en: "The revised Data Protection Act (nDSG) ruled out commercial cloud LLMs for confidential client files.",
    },
    solution: {
      de: "Private Open-Weight-Modelle mit lokalen Vektor-Embeddings, betrieben in einem Tier-IV-Rechenzentrum in der Schweiz.",
      en: "Private open-weight models with local vector embeddings, operated in a Swiss tier-IV data centre.",
    },
    outcomes: {
      de: [
        "Null Telemetrie über die Landesgrenze – nDSG- und DSGVO-konform",
        "85 % weniger Zeit für die initiale Due-Diligence",
        "Analyse auf Deutsch, Französisch, Italienisch und Englisch",
      ],
      en: [
        "Zero telemetry crosses the border – nDSG and GDPR compliant",
        "85% less time spent on initial due diligence",
        "Analysis in German, French, Italian and English",
      ],
    },
    metrics: [
      { value: "85%", label: { de: "Schnellere Due Diligence", en: "Faster due diligence" } },
      { value: "4", label: { de: "Landessprachen", en: "Languages" } },
      { value: "0", label: { de: "Datenabfluss", en: "Data egress" } },
    ],
    tech: ["Private LLMs", "pgvector", "RAG", "FastAPI", "Swiss Cloud"],
    hue: "#2B4BFF",
    motif: "rings",
  },
  {
    slug: "helvetia-biosystems",
    num: "04",
    client: "Helvetia Biosystems",
    title: {
      de: "Diagnostik-Workstation für klinische Forschung",
      en: "Diagnostic workstation for clinical research",
    },
    category: "Plattform",
    sector: { de: "Life Sciences", en: "Life Sciences" },
    location: "Basel · Genf",
    year: "2025",
    summary: {
      de: "GPU-beschleunigte Web-Workstation für Labore in Basel und Genf, die über 500'000 Datenpunkte flüssig mit 60 FPS darstellt.",
      en: "GPU-accelerated web workstation for labs in Basel and Geneva, rendering 500,000+ data points at a smooth 60 FPS.",
    },
    challenge: {
      de: "Schwerfällige Desktop-Software verhinderte die Zusammenarbeit über institutionelle Studien hinweg.",
      en: "Clunky desktop software blocked collaboration across institutional trials.",
    },
    solution: {
      de: "Web-Anwendung mit WebGL-Shadern für die Datenvisualisierung und revisionssicherem Audit-Logging.",
      en: "Web application with WebGL data shaders and tamper-proof audit logging.",
    },
    outcomes: {
      de: [
        "Im Einsatz an 18 Forschungsspitälern und Laboren",
        "12× schnellere Auswertung onkologischer Assays",
        "Audit-Logging nach Swissmedic- und 21-CFR-Part-11-Vorgaben",
      ],
      en: [
        "In use at 18 research hospitals and labs",
        "12× faster analysis of oncology assays",
        "Audit logging to Swissmedic and 21 CFR Part 11 standards",
      ],
    },
    metrics: [
      { value: "60fps", label: { de: "bei 500k Punkten", en: "at 500k points" } },
      { value: "18", label: { de: "Institute", en: "Institutes" } },
      { value: "12×", label: { de: "Schneller", en: "Faster" } },
    ],
    tech: ["WebGL", "TypeScript", "Next.js", "GPU", "Audit Logging"],
    hue: "#00A86B",
    motif: "grid",
  },
  {
    slug: "gotthard-mobility",
    num: "05",
    client: "Gotthard Transit",
    title: {
      de: "Flotten- & Ladeorchestrierung für E-Busse",
      en: "Fleet & charging orchestration for e-buses",
    },
    category: "Infrastruktur",
    sector: { de: "Öffentlicher Verkehr", en: "Public Transport" },
    location: "Uri · Tessin",
    year: "2024",
    summary: {
      de: "Ladeplanung und Disposition für elektrische Busflotten, abgestimmt auf Netzlast und kommunale Stromtarife.",
      en: "Charge scheduling and dispatch for electric bus fleets, aligned with grid load and municipal tariffs.",
    },
    challenge: {
      de: "Lastspitzen im Depot vermeiden und trotzdem jeden Morgen 100 % Einsatzbereitschaft garantieren.",
      en: "Avoid depot peak loads while guaranteeing 100% readiness every morning.",
    },
    solution: {
      de: "Prädiktiver Planungsalgorithmus mit Echtzeit-Leitstand, automatischem Lastabwurf und Umplanung.",
      en: "Predictive scheduling with a real-time control room, automatic load shedding and re-routing.",
    },
    outcomes: {
      de: [
        "35 % geringere Spitzenlast in allen Depots",
        "Kein verpasster Kurs auf 220'000 Fahrzeugkilometern",
        "Kontrastreicher, barrierefreier Leitstand",
      ],
      en: [
        "35% lower peak load across all depots",
        "Zero missed departures over 220,000 vehicle km",
        "High-contrast, accessible control room",
      ],
    },
    metrics: [
      { value: "−35%", label: { de: "Spitzenlast", en: "Peak load" } },
      { value: "220k", label: { de: "km ohne Ausfall", en: "km, zero misses" } },
      { value: "24/7", label: { de: "Leitstand", en: "Control room" } },
    ],
    tech: ["IoT", "React", "Node.js", "Time-Series DB", "Forecasting"],
    hue: "#FF6A00",
    motif: "cross",
  },
];

export interface Service {
  slug: string;
  num: string;
  title: Bi;
  lead: Bi;
  items: { de: string[]; en: string[] };
  tech: string[];
  href?: string;
}

export const SERVICES: Service[] = [
  {
    slug: "web",
    num: "01",
    title: { de: "Webplattformen & Websites", en: "Web platforms & websites" },
    lead: {
      de: "Markenwebsites, Portale und SaaS-Produkte mit Next.js – schnell, barrierefrei und auf Google ausgerichtet.",
      en: "Brand websites, portals and SaaS products in Next.js – fast, accessible and built to rank.",
    },
    items: {
      de: ["Corporate Websites & Kampagnen", "Kundenportale & Dashboards", "SaaS- & Multi-Tenant-Architektur", "Headless CMS & E-Commerce"],
      en: ["Corporate websites & campaigns", "Customer portals & dashboards", "SaaS & multi-tenant architecture", "Headless CMS & e-commerce"],
    },
    tech: ["Next.js", "TypeScript", "React", "PostgreSQL"],
    href: "/webagentur-zuerich",
  },
  {
    slug: "design",
    num: "02",
    title: { de: "Webdesign & Design Systems", en: "Web design & design systems" },
    lead: {
      de: "Klare Typografie, präzises Raster und Interaktionen, die man spürt. Schweizer Grafikstil für digitale Produkte.",
      en: "Clear typography, a precise grid and interactions you can feel. Swiss graphic style for digital products.",
    },
    items: {
      de: ["Art Direction & Markenauftritt", "UI/UX & Prototyping", "Design-Token-Systeme", "Barrierefreiheit (WCAG 2.2)"],
      en: ["Art direction & brand identity", "UI/UX & prototyping", "Design token systems", "Accessibility (WCAG 2.2)"],
    },
    tech: ["Figma", "Motion", "Tokens", "WCAG 2.2"],
    href: "/webdesign-agentur-schweiz",
  },
  {
    slug: "software",
    num: "03",
    title: { de: "Software & App-Entwicklung", en: "Software & app development" },
    lead: {
      de: "Individualsoftware und Apps für Prozesse, die Standardlösungen nicht abbilden – mit vollem Quellcode-Eigentum.",
      en: "Custom software and apps for processes off-the-shelf tools can't handle – with full source code ownership.",
    },
    items: {
      de: ["Web- & Mobile-Apps", "Prozessautomatisierung", "Schnittstellen & ERP-Integration", "Modernisierung von Altsystemen"],
      en: ["Web & mobile apps", "Process automation", "APIs & ERP integration", "Legacy modernisation"],
    },
    tech: ["React Native", "Node.js", "APIs", "Cloud"],
    href: "/software-agentur-zuerich",
  },
  {
    slug: "ai",
    num: "04",
    title: { de: "Enterprise AI & private LLMs", en: "Enterprise AI & private LLMs" },
    lead: {
      de: "KI-Assistenten und RAG-Systeme, die in Schweizer Rechenzentren laufen. Ihre Daten bleiben in der Schweiz.",
      en: "AI assistants and RAG systems running in Swiss data centres. Your data stays in Switzerland.",
    },
    items: {
      de: ["Private Sprachmodelle", "Wissenssuche (RAG)", "Agenten & Copilots", "nDSG-konforme Architektur"],
      en: ["Private language models", "Knowledge search (RAG)", "Agents & copilots", "nDSG-compliant architecture"],
    },
    tech: ["Llama", "Mistral", "pgvector", "Python"],
    href: "/enterprise-ai-schweiz",
  },
  {
    slug: "cloud",
    num: "05",
    title: { de: "Cloud, Hosting & Betrieb", en: "Cloud, hosting & operations" },
    lead: {
      de: "Hochverfügbare Infrastruktur mit Datenhaltung in der Schweiz, automatisierten Deployments und Monitoring.",
      en: "Highly available infrastructure with Swiss data residency, automated deployments and monitoring.",
    },
    items: {
      de: ["Swiss Hosting (Zürich, Genf)", "Kubernetes & Terraform", "CI/CD ohne Downtime", "Monitoring & SLA"],
      en: ["Swiss hosting (Zurich, Geneva)", "Kubernetes & Terraform", "Zero-downtime CI/CD", "Monitoring & SLA"],
    },
    tech: ["AWS Zürich", "Exoscale", "Terraform", "Kubernetes"],
  },
];

export const PROCESS: { num: string; title: Bi; text: Bi; time: Bi }[] = [
  {
    num: "01",
    title: { de: "Verstehen", en: "Understand" },
    text: {
      de: "Workshop mit Ihrem Team. Ziele, Nutzer, Systeme und Risiken – kompakt auf einer Seite.",
      en: "A workshop with your team. Goals, users, systems and risks – on a single page.",
    },
    time: { de: "Woche 1", en: "Week 1" },
  },
  {
    num: "02",
    title: { de: "Gestalten", en: "Design" },
    text: {
      de: "Art Direction, Prototyp und Architektur. Sie klicken durch das Produkt, bevor eine Zeile Code entsteht.",
      en: "Art direction, prototype and architecture. You click through the product before a line of code is written.",
    },
    time: { de: "Woche 2–3", en: "Weeks 2–3" },
  },
  {
    num: "03",
    title: { de: "Bauen", en: "Build" },
    text: {
      de: "Zweiwöchige Sprints, jeden Freitag eine Live-Version auf Staging. Kein Blindflug.",
      en: "Two-week sprints with a live staging release every Friday. No flying blind.",
    },
    time: { de: "Woche 4–10", en: "Weeks 4–10" },
  },
  {
    num: "04",
    title: { de: "Lancieren", en: "Launch" },
    text: {
      de: "Go-Live mit Lasttests, SEO-Migration und Monitoring. Danach gehört der Code Ihnen – zu 100 %.",
      en: "Go-live with load tests, SEO migration and monitoring. Then the code is yours – 100%.",
    },
    time: { de: "Woche 10+", en: "Week 10+" },
  },
];

export const FAQ: { q: Bi; a: Bi }[] = [
  {
    q: {
      de: "Was kostet eine Website oder Webapplikation bei SHAZWERK?",
      en: "How much does a website or web app cost at SHAZWERK?",
    },
    a: {
      de: "Jedes Projekt erhält nach einem kostenlosen Erstgespräch ein Festpreis-Angebot pro Meilenstein. So wissen Sie vor dem Start genau, was Sie erhalten und was es kostet.",
      en: "After a free initial call, every project receives a fixed-price proposal per milestone, so you know exactly what you get and what it costs before we start.",
    },
  },
  {
    q: {
      de: "Wie lange dauert ein typisches Projekt?",
      en: "How long does a typical project take?",
    },
    a: {
      de: "Eine Markenwebsite ist meist in 4 bis 6 Wochen live, eine Webplattform oder ein MVP in 8 bis 12 Wochen. Wir arbeiten in zweiwöchigen Sprints mit wöchentlichen Staging-Releases.",
      en: "A brand website usually goes live in 4 to 6 weeks, a web platform or MVP in 8 to 12 weeks. We work in two-week sprints with weekly staging releases.",
    },
  },
  {
    q: {
      de: "Bleiben unsere Daten in der Schweiz (nDSG)?",
      en: "Does our data stay in Switzerland (nDSG)?",
    },
    a: {
      de: "Ja. Wir hosten auf Schweizer Infrastruktur (AWS Zürich, Exoscale, Infomaniak) und betreiben KI-Modelle privat – konform mit dem revidierten Datenschutzgesetz (nDSG) und der DSGVO.",
      en: "Yes. We host on Swiss infrastructure (AWS Zurich, Exoscale, Infomaniak) and run AI models privately – compliant with the revised Data Protection Act (nDSG) and GDPR.",
    },
  },
  {
    q: {
      de: "Wem gehört der Quellcode nach Projektabschluss?",
      en: "Who owns the source code after the project?",
    },
    a: {
      de: "Ihnen. 100 % des Quellcodes und des geistigen Eigentums werden übertragen. Kein Vendor Lock-in, keine Lizenzgebühren.",
      en: "You do. 100% of source code and intellectual property is transferred. No vendor lock-in, no licence fees.",
    },
  },
  {
    q: {
      de: "Arbeiten Sie auch für KMU und Start-ups?",
      en: "Do you work with SMEs and start-ups?",
    },
    a: {
      de: "Ja. Wir arbeiten mit Schweizer KMU, Scale-ups und Konzernen in Zürich, Zug, Basel, Bern, Luzern und Genf – vor Ort oder remote, auf Deutsch, Englisch oder Französisch.",
      en: "Yes. We work with Swiss SMEs, scale-ups and enterprises in Zurich, Zug, Basel, Bern, Lucerne and Geneva – on site or remote, in German, English or French.",
    },
  },
];

export const CLIENT_SECTORS = [
  "Banking",
  "Insurance",
  "Pharma",
  "MedTech",
  "Logistik",
  "Legal",
  "Real Estate",
  "Public Sector",
  "Retail",
  "Energy",
];
